### ISSUE TITLE
New Feature?

### ISSUE THREAD

**Issue by 19216800** [schliesser/fs-admintoolbox#7]
Probably doing wrong. Download zip added to server, server returns
> _Uploaded mod file not supported. Only Farming Simulator 22 mods are supported._ 

Is this mod still active and maintained? And/or how would one go about adding it to their server?

**Comment by schliesser** [comment]
Hey @19216800 , did you use the Github-Zip Download Button?
I think this will pack the mod incorrectly

![image](https://user-images.githubusercontent.com/11655823/209777955-52bf6ac9-2291-4b21-8ac8-efb6444af587.png)


Please use the Download on the releases page:
https://github.com/schliesser/fs-admintoolbox/releases/tag/v1.0.0.0-alpha.3

![image](https://user-images.githubusercontent.com/11655823/209778138-6b4f9ca8-8d37-464a-837d-9644b1154183.png)

Can you confirm which download you used?
I have very little time to continue the development, but would like to do so in future.

**Comment by 19216800** [comment]
Oh my yes I used the git download. Dont know why I didn't check the release. I will retry later today.
Sorry about that, but thanks for taking the time.

**Comment by 19216800** [comment]
Hey sorry to bother again, I need to thank you again for the tool works great in the server. 
I was wondering if the feature super strength be add as I run into stuck items from other players that could use an admin super strength.

**Anyhow take care Happy New Years**

**Comment by schliesser** [comment]
@19216800 you're welcome. Please have a look at the Power Tools mod for the super-strengh feature. I wont implement it again, as the state to switch it on/off can't be saved globally. 
https://www.farming-simulator.com/mod.php?mod_id=224578

Happy New Years 🎉
